[package]
name = "solitaire_solvability"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_derive = "1"
rand = "0.8"
colored = "2.0.0"
derivative = "2.2.0"